version: "3"

volumes:
  dbbackups:
  postgis-data:
  session-redis:
  mysql-data:
  cache:
services:
  main:
    image: getme-main
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - default
    volumes:
      - ./api:/app/api
      - ./logs:/app/logs
      - ./media:/app/media
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - getme-db
      - session-service
      - getme-cache
    environment:
      WAIT_HOSTS: getme-db:5432, getme-cache:6379

  session-service:
    image: session-service
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - default
    volumes:
      - ./logs-sessions:/app/logs
      - ${CONFIG_DIR}:/app/configs
    depends_on:
      - session-redis
    environment:
      WAIT_HOSTS: getme-db:5432
  getme-db:
    image: pg-14
    expose:
      - "5430"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${PG_BD_PASSWORD}
      - POSTGRES_USER=${PG_BD_USERNAME}
      - POSTGRES_DB=${PG_BD_NAME}
    ports:
      - "5430:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 5G
  session-redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - session-redis:/data
    restart: always

  getme-cache:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - cache:/data
    restart: always

networks:
  default:
    driver: bridge